### PR TITLE
Fix return type PHPDoc in Algorithm/Manager

### PR DESCRIPTION
**Pull request by TimWolla**
Not sure if this is the correct place to put my PR, but the cose-lib is no longer part of the main repository.

### CODE REVIEW

**Comment by Spomky** [comment]
Many thanks.
Yes this is the good place. I decoupled the libraries from webauthn repository as there is not much modifications but versions were still going up (for no reason).

**Comment by TimWolla** [comment]
> Yes this is the good place. I decoupled the libraries from webauthn repository as there is not much modifications but versions were still going up (for no reason).

Okay, then you should delete https://github.com/web-auth/cose-lib/blob/v4.0/.github/PULL_REQUEST_TEMPLATE.md and also update the repository description to remove the `[READ ONLY]`.

Also, thanks for creating the WebAuthn framework!

**Comment by Spomky** [comment]
Hi @TimWolla,

It will be settled.
I will add issue/PR templates and other necessary files.

Regards.

**Comment by Spomky** [comment]
Done. Project files added/changed.

**Pull request merged**
