### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by szepeviktor**
All my knowledge in a single PR :)

kép

Previously CI UI was non-informative.

kép

You could use this CI config in your other projects. It needs very little work.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Working on possible problems in https://github.com/szepeviktor/web-auth_cose-lib/pull/1

**Comment by szepeviktor** [comment]
@Spomky I could work on

- static analysis problems
- and setting up Coveralls to get hold of coverage details

**Comment by Spomky** [comment]
Excellent!
I did something similare for another project, but the way you implement it is much nicer.

**Comment by szepeviktor** [comment]
I'd happily repeat this anytime.

**Pull request merged**
